engines:
    fixme:
        enabled: true
    gofmt:
        enabled: true
    golint:
        enabled: true
    govet:
        enabled: true

ratings:
  paths:
  - ".go"

exclude_paths:
- "api_test.go"
- "bot_test.go"
- "direct_message_test.go"
- "error_test.go"
- "event_test.go"
- "listen_test.go"
- "mention_test.go"
- "message_test.go"
- "respond_test.go"
